[package]
name = "solopass_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.5.11"
cosmwasm-schema = "1.5.11"
serde = { version = "1.0", features = ["derive"] }
serde-json-wasm = "0.5.2"
schemars = "0.8"
thiserror = "1.0"

